### ISSUE TITLE
Configuration behavior question

### ISSUE THREAD

**Issue by athurdent** [Kienz/homebridge-unifi-poe-control#4]
First of all, thank you very much for this awesome plugin!
I ran into the problem that my web GUI configuration was overwritten by the plugin. E.g. I configured a port and shortly after toggled a PoE port with the Home app.
It seems that the plugin always sends the complete, cached port configuration of all switch ports instead of configuring the single port I modify PoE for. If the cached configuration is older than the actual configuration, web GUI modifications get overwritten.
Is it possible to configure only one single port instead of all ports, or does the API not allow for that?
Thanks!

**Comment by Kienz** [comment]
I have to dig deeper into the UniFi api. Maybe it’s possible to just edit one port configuration. 
What I have seen so far you can only change all "port_overrides" at once. There seems to be another problem - see #3.

Otherwise I have to call the api to get current config and only update If config of the port is changed. I think I can fix this in the next release.

**Comment by Kienz** [comment]
Fixed (Release v1.2.0)
